name: PortalNetwork
version: '${version}'
main: au.com.grieve.portalnetwork.PortalNetwork
api-version: "1.13"
authors: [Bundabrg,Glob]
description: Allow one to create portals that can easily be linked to each other using colours.
